/**
 * Centralized Error Code Registry
 * Prevents hardcoded strings and maintains consistency across the application
 */

export const ERROR_CODES = {
  // Client Errors (4xx)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  // Server Errors (5xx)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',

  // Business Logic Errors
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',

  // Data Integrity Errors
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  REFERENTIAL_INTEGRITY_VIOLATION: 'REFERENTIAL_INTEGRITY_VIOLATION',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',

  // Network & Communication Errors
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  DNS_RESOLUTION_FAILED: 'DNS_RESOLUTION_FAILED',

  // Cache Errors
  CACHE_MISS: 'CACHE_MISS',
  CACHE_ERROR: 'CACHE_ERROR',

  // File System Errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',

  // Security Errors
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Configuration Errors
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  ENVIRONMENT_VARIABLE_MISSING: 'ENVIRONMENT_VARIABLE_MISSING',

  // Monitoring & Observability
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
  DEPENDENCY_UNHEALTHY: 'DEPENDENCY_UNHEALTHY'
};

// Helper function to validate error codes
export const isValidErrorCode = (code) => {
  return Object.values(ERROR_CODES).includes(code);
};

// Helper function to get error category
export const getErrorCategory = (code) => {
  if (code.startsWith('4') || code.includes('VALIDATION') || code.includes('UNAUTHORIZED') || code.includes('FORBIDDEN')) {
    return 'CLIENT_ERROR';
  }
  if (code.startsWith('5') || code.includes('INTERNAL') || code.includes('DATABASE') || code.includes('EXTERNAL')) {
    return 'SERVER_ERROR';
  }
  return 'UNKNOWN';
};

export default ERROR_CODES;
