/**
 * Moderation System Data Transfer Objects
 * Week-3 Ownership Feature Build
 * Clean API contracts and validation schemas
 */

import { REPORT_SEVERITY, REPORT_STATUS, ACTION_TYPE, TRUST_LEVEL, APPEAL_STATUS, FLAG_TYPE } from './constants.js';

export const reportDto = {
  create: (data) => ({
    reporterId: data.reporterId,
    reportedUserId: data.reportedUserId,
    reportedPostId: data.reportedPostId,
    reportedCommentId: data.reportedCommentId,
    severity: data.severity || REPORT_SEVERITY.MEDIUM,
    flagType: data.flagType,
    reason: data.reason,
    description: data.description,
    evidenceUrls: data.evidenceUrls || []
  }),

  list: (report) => ({
    id: report.id,
    severity: report.severity,
    status: report.status,
    flagType: report.flagType,
    reason: report.reason,
    isDuplicate: report.isDuplicate,
    autoGenerated: report.autoGenerated,
    createdAt: report.createdAt,
    updatedAt: report.updatedAt,
    reportedUser: report.reportedUser ? {
      id: report.reportedUser.id,
      name: report.reportedUser.name,
      email: report.reportedUser.email
    } : null,
    reportedPost: report.reportedPost ? {
      id: report.reportedPost.id,
      title: report.reportedPost.title
    } : null,
    reportedComment: report.reportedComment ? {
      id: report.reportedComment.id,
      content: report.reportedComment.content.substring(0, 100) + '...'
    } : null,
    moderationCase: report.moderationCase ? {
      id: report.moderationCase.id,
      caseNumber: report.moderationCase.caseNumber,
      state: report.moderationCase.state
    } : null
  }),

  detail: (report) => ({
    id: report.id,
    severity: report.severity,
    status: report.status,
    flagType: report.flagType,
    reason: report.reason,
    description: report.description,
    evidenceUrls: report.evidenceUrls,
    isDuplicate: report.isDuplicate,
    duplicateOfId: report.duplicateOfId,
    autoGenerated: report.autoGenerated,
    createdAt: report.createdAt,
    updatedAt: report.updatedAt,
    reporter: report.reporter ? {
      id: report.reporter.id,
      name: report.reporter.name,
      email: report.reporterUser.email
    } : null,
    reportedUser: report.reportedUser ? {
      id: report.reportedUser.id,
      name: report.reportedUser.name,
      email: report.reportedUser.email
    } : null,
    reportedPost: report.reportedPost,
    reportedComment: report.reportedComment,
    moderationCase: report.moderationCase
  })
};

export const caseDto = {
  create: (data) => ({
    title: data.title,
    description: data.description,
    priority: data.priority || REPORT_SEVERITY.MEDIUM,
    assignedModeratorId: data.assignedModeratorId,
    autoGenerated: data.autoGenerated || false
  }),

  list: (case_) => ({
    id: case_.id,
    caseNumber: case_.caseNumber,
    title: case_.title,
    priority: case_.priority,
    state: case_.state,
    autoGenerated: case_.autoGenerated,
    createdAt: case_.createdAt,
    updatedAt: case_.updatedAt,
    assignedModerator: case_.assignedModerator ? {
      id: case_.assignedModerator.id,
      name: case_.assignedModerator.name
    } : null,
    reportCount: case_.reports?.length || 0,
    actionCount: case_.actions?.length || 0
  }),

  detail: (case_) => ({
    id: case_.id,
    caseNumber: case_.caseNumber,
    title: case_.title,
    description: case_.description,
    priority: case_.priority,
    state: case_.state,
    escalatedToAdmin: case_.escalatedToAdmin,
    autoGenerated: case_.autoGenerated,
    createdAt: case_.createdAt,
    updatedAt: case_.updatedAt,
    resolvedAt: case_.resolvedAt,
    assignedModerator: case_.assignedModerator,
    escalatedAdmin: case_.escalatedAdmin,
    reports: case_.reports?.map(reportDto.list) || [],
    actions: case_.actions?.map(actionDto.list) || [],
    appeals: case_.appeals?.map(appealDto.list) || []
  })
};

export const actionDto = {
  create: (data) => ({
    moderationCaseId: data.moderationCaseId,
    moderatorId: data.moderatorId,
    actionType: data.actionType,
    actionDetails: data.actionDetails,
    targetUserId: data.targetUserId,
    targetContentType: data.targetContentType,
    targetContentId: data.targetContentId,
    durationDays: data.durationDays,
    trustScoreChange: data.trustScoreChange || 0,
    isAutomatic: data.isAutomatic || false,
    systemReason: data.systemReason
  }),

  list: (action) => ({
    id: action.id,
    actionType: action.actionType,
    targetContentType: action.targetContentType,
    targetContentId: action.targetContentId,
    durationDays: action.durationDays,
    trustScoreChange: action.trustScoreChange,
    isAutomatic: action.isAutomatic,
    createdAt: action.createdAt,
    moderator: action.moderator ? {
      id: action.moderator.id,
      name: action.moderator.name
    } : null,
    targetUser: action.targetUser ? {
      id: action.targetUser.id,
      name: action.targetUser.name
    } : null
  }),

  detail: (action) => ({
    id: action.id,
    actionType: action.actionType,
    actionDetails: action.actionDetails,
    targetContentType: action.targetContentType,
    targetContentId: action.targetContentId,
    durationDays: action.durationDays,
    trustScoreChange: action.trustScoreChange,
    isAutomatic: action.isAutomatic,
    systemReason: action.systemReason,
    createdAt: action.createdAt,
    moderator: action.moderator,
    targetUser: action.targetUser,
    moderationCase: action.moderationCase ? {
      id: action.moderationCase.id,
      caseNumber: action.moderationCase.caseNumber
    } : null
  })
};

export const trustScoreDto = {
  list: (trustScore) => ({
    userId: trustScore.userId,
    overallScore: trustScore.overallScore,
    trustLevel: trustScore.trustLevel,
    contentQualityScore: trustScore.contentQualityScore,
    communityEngagementScore: trustScore.communityEngagementScore,
    reliabilityScore: trustScore.reliabilityScore,
    lastCalculatedAt: trustScore.lastCalculatedAt
  }),

  detail: (trustScore) => ({
    id: trustScore.id,
    userId: trustScore.userId,
    overallScore: trustScore.overallScore,
    trustLevel: trustScore.trustLevel,
    contentQualityScore: trustScore.contentQualityScore,
    communityEngagementScore: trustScore.communityEngagementScore,
    reliabilityScore: trustScore.reliabilityScore,
    lastCalculatedAt: trustScore.lastCalculatedAt,
    createdAt: trustScore.createdAt,
    updatedAt: trustScore.updatedAt,
    user: trustScore.user ? {
      id: trustScore.user.id,
      name: trustScore.user.name,
      email: trustScore.user.email
    } : null
  })
};

export const appealDto = {
  create: (data) => ({
    moderationCaseId: data.moderationCaseId,
    appellantUserId: data.appellantUserId,
    originalActionId: data.originalActionId,
    appealReason: data.appealReason,
    appealDescription: data.appealDescription,
    evidenceUrls: data.evidenceUrls || []
  }),

  list: (appeal) => ({
    id: appeal.id,
    status: appeal.status,
    appealReason: appeal.appealReason,
    finalDecision: appeal.finalDecision,
    createdAt: appeal.createdAt,
    updatedAt: appeal.updatedAt,
    resolvedAt: appeal.resolvedAt,
    appellant: appeal.appellant ? {
      id: appeal.appellant.id,
      name: appeal.appellant.name
    } : null,
    moderationCase: appeal.moderationCase ? {
      id: appeal.moderationCase.id,
      caseNumber: appeal.moderationCase.caseNumber
    } : null
  }),

  detail: (appeal) => ({
    id: appeal.id,
    status: appeal.status,
    appealReason: appeal.appealReason,
    appealDescription: appeal.appealDescription,
    evidenceUrls: appeal.evidenceUrls,
    reviewNotes: appeal.reviewNotes,
    finalDecision: appeal.finalDecision,
    createdAt: appeal.createdAt,
    updatedAt: appeal.updatedAt,
    resolvedAt: appeal.resolvedAt,
    appellant: appeal.appellant,
    moderationCase: appeal.moderationCase,
    originalAction: appeal.originalAction,
    reviewingModerator: appeal.reviewingModerator
  })
};

export const dashboardDto = {
  summary: (data) => ({
    totalCases: data.totalCases,
    activeCases: data.activeCases,
    pendingReports: data.pendingReports,
    resolvedToday: data.resolvedToday,
    escalatedCases: data.escalatedCases,
    averageResolutionTime: data.averageResolutionTime,
    moderatorWorkload: data.moderatorWorkload,
    trustScoreDistribution: data.trustScoreDistribution,
    recentActivity: data.recentActivity
  }),

  caseList: (cases) => cases.map(caseDto.list),

  reportList: (reports) => reports.map(reportDto.list),

  actionList: (actions) => actions.map(actionDto.list)
};
