/**
 * Moderation System Service Layer
 * Week-3 Ownership Feature Build
 * Business logic and trust scoring algorithms
 */

import { ApiError } from '../../utils/ApiError.js';
import { ApiResponse } from '../../utils/ApiResponse.js';
import { paginate } from '../../utils/pagination.js';
import ModerationPolicy from './policies.js';
import { 
  REPORT_SEVERITY, 
  REPORT_STATUS, 
  CASE_STATE, 
  ACTION_TYPE, 
  TRUST_LEVEL, 
  APPEAL_STATUS, 
  FLAG_TYPE,
  LOG_TYPE,
  TRUST_THRESHOLDS,
  AUTO_FLAG_THRESHOLDS,
  SUSPENSION_DURATIONS
} from './constants.js';
import { reportDto, caseDto, actionDto, trustScoreDto, appealDto, dashboardDto } from './dto.js';

class ModerationService {
  constructor(prisma, activityService) {
    this.prisma = prisma;
    this.activityService = activityService;
  }

  // ========================================
  // REPORT MANAGEMENT
  // ========================================

  async createReport(reportData, reporterId) {
    // Check for duplicate reports
    const existingReport = await this.findDuplicateReport(reportData, reporterId);
    if (existingReport) {
      throw new ApiError(409, 'Duplicate report already exists');
    }

    // Check rate limiting
    const recentReports = await this.getRecentReportsByUser(reporterId, 1); // 1 hour
    if (ModerationPolicy.isRateLimitedForReports({ id: reporterId }, recentReports)) {
      throw new ApiError(429, 'Rate limit exceeded for reports');
    }

    // Auto-generate moderation case if severity is HIGH or CRITICAL
    const shouldCreateCase = reportData.severity === REPORT_SEVERITY.HIGH || 
                            reportData.severity === REPORT_SEVERITY.CRITICAL;

    const report = await this.prisma.report.create({
      data: {
        ...reportDto.create(reportData),
        reporterId,
        moderationCaseId: shouldCreateCase ? null : undefined // Will be set if case is created
      },
      include: {
        reporter: true,
        reportedUser: true,
        reportedPost: true,
        reportedComment: true,
        moderationCase: true
      }
    });

    // Create moderation case if needed
    let moderationCase = null;
    if (shouldCreateCase) {
      moderationCase = await this.createModerationCase({
        title: `Auto-generated case for ${reportData.flagType} report`,
        description: `Automatically created due to ${reportData.severity} severity report`,
        priority: reportData.severity,
        autoGenerated: true
      });

      // Link report to case
      await this.prisma.report.update({
        where: { id: report.id },
        data: { moderationCaseId: moderationCase.id }
      });

      report.moderationCase = moderationCase;
    }

    // Log the action
    await this.logAction(LOG_TYPE.REPORT_SUBMITTED, {
      reportId: report.id,
      reporterId,
      autoCaseCreated: shouldCreateCase
    }, reporterId);

    // Auto-flag content if confidence is high
    await this.autoFlagContent(report);

    return reportDto.detail(report);
  }

  async getReportById(reportId, user) {
    const report = await this.prisma.report.findUnique({
      where: { id: reportId },
      include: {
        reporter: true,
        reportedUser: true,
        reportedPost: true,
        reportedComment: true,
        moderationCase: {
          include: {
            assignedModerator: true,
            actions: true
          }
        }
      }
    });

    if (!report) {
      throw new ApiError(404, 'Report not found');
    }

    // Check access permissions
    if (!ModerationPolicy.isModerator(user) && report.reporterId !== user.id) {
      throw new ApiError(403, 'Access denied');
    }

    return reportDto.detail(report);
  }

  async getReports(filters, user) {
    const { skip, limit, page } = paginate(filters);
    
    // Build where clause
    const where = {};
    if (filters.status) where.status = filters.status;
    if (filters.severity) where.severity = filters.severity;
    if (filters.flagType) where.flagType = filters.flagType;
    if (filters.reportedUserId) where.reportedUserId = filters.reportedUserId;

    const reports = await this.prisma.report.findMany({
      where,
      skip,
      take: limit,
      orderBy: { createdAt: 'desc' },
      include: {
        reporter: true,
        reportedUser: true,
        reportedPost: true,
        reportedComment: true,
        moderationCase: true
      }
    });

    const totalReports = await this.prisma.report.count({ where });

    return {
      reports: reports.map(reportDto.list),
      meta: { page, limit, totalReports, totalPages: Math.ceil(totalReports / limit) }
    };
  }

  // ========================================
  // MODERATION CASE MANAGEMENT
  // ========================================

  async createModerationCase(caseData, createdBy = null) {
    const moderationCase = await this.prisma.moderationCase.create({
      data: caseDto.create(caseData),
      include: {
        assignedModerator: true,
        reports: true,
        actions: true,
        appeals: true
      }
    });

    // Log case creation
    await this.logAction(LOG_TYPE.CASE_CREATED, {
      caseId: moderationCase.id,
      caseNumber: moderationCase.caseNumber,
      autoGenerated: caseData.autoGenerated
    }, createdBy);

    return caseDto.detail(moderationCase);
  }

  async assignModerationCase(caseId, moderatorId, assignedBy) {
    if (!ModerationPolicy.canAssignCases({ id: assignedBy })) {
      throw new ApiError(403, 'Insufficient permissions to assign cases');
    }

    const moderationCase = await this.prisma.moderationCase.update({
      where: { id: caseId },
      data: { 
        assignedModeratorId: moderatorId,
        state: CASE_STATE.ASSIGNED
      },
      include: {
        assignedModerator: true,
        reports: true,
        actions: true
      }
    });

    // Log assignment
    await this.logAction(LOG_TYPE.CASE_ASSIGNED, {
      caseId,
      moderatorId,
      assignedBy
    }, assignedBy);

    return caseDto.detail(moderationCase);
  }

  async takeModerationAction(caseId, actionData, moderatorId) {
    const moderationCase = await this.prisma.moderationCase.findUnique({
      where: { id: caseId },
      include: { assignedModerator: true }
    });

    if (!moderationCase) {
      throw new ApiError(404, 'Moderation case not found');
    }

    if (!ModerationPolicy.canAccessCase({ id: moderatorId }, moderationCase)) {
      throw new ApiError(403, 'Access denied to this case');
    }

    if (!ModerationPolicy.canTakeAction({ id: moderatorId }, actionData.actionType)) {
      throw new ApiError(403, 'Insufficient permissions for this action');
    }

    // Validate action constraints
    const validationErrors = ModerationPolicy.validateActionConstraints(
      actionData.actionType, 
      actionData
    );
    if (validationErrors.length > 0) {
      throw new ApiError(400, `Validation failed: ${validationErrors.join(', ')}`);
    }

    // Execute the action
    const action = await this.executeModerationAction(actionData, caseId, moderatorId);

    // Update case state if needed
    await this.updateCaseStateAfterAction(caseId, actionData.actionType);

    return actionDto.detail(action);
  }

  async resolveModerationCase(caseId, resolutionData, resolvedBy) {
    const moderationCase = await this.prisma.moderationCase.findUnique({
      where: { id: caseId },
      include: { assignedModerator: true }
    });

    if (!moderationCase) {
      throw new ApiError(404, 'Moderation case not found');
    }

    if (!ModerationPolicy.canResolveCase({ id: resolvedBy }, moderationCase)) {
      throw new ApiError(403, 'Cannot resolve this case');
    }

    const updatedCase = await this.prisma.moderationCase.update({
      where: { id: caseId },
      data: {
        state: resolutionData.finalStatus || CASE_STATE.RESOLVED,
        resolvedAt: new Date()
      },
      include: {
        assignedModerator: true,
        reports: true,
        actions: true,
        appeals: true
      }
    });

    // Log resolution
    await this.logAction(LOG_TYPE.ACTION_TAKEN, {
      caseId,
      action: 'case_resolved',
      resolutionNotes: resolutionData.resolutionNotes,
      resolvedBy
    }, resolvedBy);

    return caseDto.detail(updatedCase);
  }

  // ========================================
  // TRUST SCORING SYSTEM
  // ========================================

  async calculateTrustScore(userId) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: {
        posts: { where: { deletedAt: null } },
        comments: { where: { deletedAt: null } },
        reportsReceived: true,
        reportsMade: true,
        trustScore: true
      }
    });

    if (!user) {
      throw new ApiError(404, 'User not found');
    }

    // Calculate component scores
    const contentQualityScore = this.calculateContentQualityScore(user);
    const communityEngagementScore = this.calculateCommunityEngagementScore(user);
    const reliabilityScore = this.calculateReliabilityScore(user);
    
    // Calculate overall score (weighted average)
    const overallScore = Math.round(
      (contentQualityScore * 0.4) + 
      (communityEngagementScore * 0.3) + 
      (reliabilityScore * 0.3)
    );

    // Determine trust level
    const trustLevel = this.determineTrustLevel(overallScore);

    // Update or create trust score record
    const trustScore = await this.prisma.trustScore.upsert({
      where: { userId },
      update: {
        overallScore,
        trustLevel,
        contentQualityScore,
        communityEngagementScore,
        reliabilityScore,
        lastCalculatedAt: new Date()
      },
      create: {
        userId,
        overallScore,
        trustLevel,
        contentQualityScore,
        communityEngagementScore,
        reliabilityScore
      }
    });

    // Log trust score update
    await this.logAction(LOG_TYPE.TRUST_UPDATED, {
      userId,
      overallScore,
      trustLevel,
      previousScore: user.trustScore?.overallScore
    });

    return trustScoreDto.detail(trustScore);
  }

  calculateContentQualityScore(user) {
    let score = 50; // Base score

    // Post quality factors
    const postCount = user.posts.length;
    if (postCount > 0) {
      score += Math.min(postCount * 2, 20); // Up to 20 points for posts
      
      // Average post length (longer, thoughtful content)
      const avgPostLength = user.posts.reduce((sum, post) => sum + post.content.length, 0) / postCount;
      if (avgPostLength > 500) score += 10;
      if (avgPostLength > 1000) score += 10;
    }

    // Comment quality factors
    const commentCount = user.comments.length;
    if (commentCount > 0) {
      score += Math.min(commentCount, 15); // Up to 15 points for comments
      
      // Average comment length
      const avgCommentLength = user.comments.reduce((sum, comment) => sum + comment.content.length, 0) / commentCount;
      if (avgCommentLength > 100) score += 5;
      if (avgCommentLength > 200) score += 5;
    }

    return Math.min(Math.max(score, 0), 100);
  }

  calculateCommunityEngagementScore(user) {
    let score = 50; // Base score

    // Reports made (helpful community participation)
    const reportsMade = user.reportsMade.length;
    if (reportsMade > 0) {
      score += Math.min(reportsMade * 3, 15);
    }

    // Account age (longer standing members)
    const accountAge = Date.now() - user.createdAt.getTime();
    const daysOld = accountAge / (1000 * 60 * 60 * 24);
    if (daysOld > 30) score += 10;
    if (daysOld > 90) score += 10;
    if (daysOld > 365) score += 15;

    return Math.min(Math.max(score, 0), 100);
  }

  calculateReliabilityScore(user) {
    let score = 50; // Base score

    // Reports against user (negative factor)
    const reportsReceived = user.reportsReceived.length;
    if (reportsReceived > 0) {
      score -= Math.min(reportsReceived * 5, 30);
    }

    // Check for user flags
    // This would need to be implemented when user_flags table is created

    return Math.min(Math.max(score, 0), 100);
  }

  determineTrustLevel(overallScore) {
    if (overallScore >= TRUST_THRESHOLDS.VIP) return TRUST_LEVEL.VIP;
    if (overallScore >= TRUST_THRESHOLDS.TRUSTED) return TRUST_LEVEL.TRUSTED;
    if (overallScore >= TRUST_THRESHOLDS.ESTABLISHED) return TRUST_LEVEL.ESTABLISHED;
    if (overallScore >= TRUST_THRESHOLDS.NEW) return TRUST_LEVEL.NEW;
    if (overallScore >= TRUST_THRESHOLDS.RESTRICTED) return TRUST_LEVEL.RESTRICTED;
    return TRUST_LEVEL.SUSPENDED;
  }

  // ========================================
  // APPEALS SYSTEM
  // ========================================

  async createAppeal(appealData, appellantUserId) {
    // Check rate limiting
    const recentAppeals = await this.getRecentAppealsByUser(appellantUserId, 7); // 7 days
    if (ModerationPolicy.isRateLimitedForAppeals({ id: appellantUserId }, recentAppeals)) {
      throw new ApiError(429, 'Rate limit exceeded for appeals');
    }

    const appeal = await this.prisma.appeal.create({
      data: appealDto.create(appealData),
      include: {
        appellant: true,
        moderationCase: true,
        originalAction: true
      }
    });

    // Log appeal filing
    await this.logAction(LOG_TYPE.APPEAL_FILED, {
      appealId: appeal.id,
      caseId: appeal.moderationCaseId,
      appellantUserId
    }, appellantUserId);

    return appealDto.detail(appeal);
  }

  async updateAppealStatus(appealId, updateData, moderatorId) {
    if (!ModerationPolicy.canReviewAppeals({ id: moderatorId })) {
      throw new ApiError(403, 'Insufficient permissions to review appeals');
    }

    const appeal = await this.prisma.appeal.update({
      where: { id: appealId },
      data: {
        ...updateData,
        reviewedByModeratorId: moderatorId,
        resolvedAt: updateData.status === APPEAL_STATUS.APPROVED || 
                   updateData.status === APPEAL_STATUS.DENIED ? new Date() : null
      },
      include: {
        appellant: true,
        moderationCase: true,
        originalAction: true,
        reviewingModerator: true
      }
    });

    return appealDto.detail(appeal);
  }

  // ========================================
  // DASHBOARD AND ANALYTICS
  // ========================================

  async getDashboardData(filters = {}) {
    const { moderatorId, dateRange = 'week' } = filters;
    
    // Calculate date range
    const now = new Date();
    let startDate = new Date();
    
    switch (dateRange) {
      case 'today':
        startDate.setHours(0, 0, 0, 0);
        break;
      case 'week':
        startDate.setDate(now.getDate() - 7);
        break;
      case 'month':
        startDate.setMonth(now.getMonth() - 1);
        break;
      case 'year':
        startDate.setFullYear(now.getFullYear() - 1);
        break;
    }

    // Get summary statistics
    const [
      totalCases,
      activeCases,
      pendingReports,
      resolvedToday,
      escalatedCases
    ] = await Promise.all([
      this.prisma.moderationCase.count({
        where: moderatorId ? { assignedModeratorId: moderatorId } : {}
      }),
      this.prisma.moderationCase.count({
        where: {
          state: { in: [CASE_STATE.OPEN, CASE_STATE.ASSIGNED, CASE_STATE.IN_PROGRESS] },
          ...(moderatorId && { assignedModeratorId: moderatorId })
        }
      }),
      this.prisma.report.count({
        where: { status: REPORT_STATUS.PENDING }
      }),
      this.prisma.moderationCase.count({
        where: {
          resolvedAt: {
            gte: new Date().setHours(0, 0, 0, 0)
          }
        }
      }),
      this.prisma.moderationCase.count({
        where: { escalatedToAdmin: true }
      })
    ]);

    // Get recent activity
    const recentActivity = await this.prisma.moderationLog.findMany({
      where: {
        createdAt: { gte: startDate },
        ...(moderatorId && { userId: moderatorId })
      },
      take: 10,
      orderBy: { createdAt: 'desc' },
      include: {
        user: { select: { id: true, name: true } }
      }
    });

    return dashboardDto.summary({
      totalCases,
      activeCases,
      pendingReports,
      resolvedToday,
      escalatedCases,
      recentActivity
    });
  }

  // ========================================
  // UTILITY METHODS
  // ========================================

  async findDuplicateReport(reportData, reporterId) {
    const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    
    return await this.prisma.report.findFirst({
      where: {
        reporterId,
        flagType: reportData.flagType,
        reportedUserId: reportData.reportedUserId,
        reportedPostId: reportData.reportedPostId,
        reportedCommentId: reportData.reportedCommentId,
        createdAt: { gte: oneDayAgo }
      }
    });
  }

  async getRecentReportsByUser(userId, hours = 1) {
    const timeAgo = new Date(Date.now() - hours * 60 * 60 * 1000);
    
    return await this.prisma.report.findMany({
      where: {
        reporterId: userId,
        createdAt: { gte: timeAgo }
      }
    });
  }

  async getRecentAppealsByUser(userId, days = 7) {
    const timeAgo = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
    
    return await this.prisma.appeal.findMany({
      where: {
        appellantUserId: userId,
        createdAt: { gte: timeAgo }
      }
    });
  }

  async autoFlagContent(report) {
    // This would integrate with AI/ML models for content analysis
    // For now, it's a placeholder for the auto-flagging logic
    
    if (report.severity === REPORT_SEVERITY.CRITICAL) {
      await this.prisma.contentFlag.create({
        data: {
          contentType: report.reportedPostId ? 'post' : 'comment',
          contentId: report.reportedPostId || report.reportedCommentId,
          flagType: report.flagType,
          confidenceScore: 95,
          autoGenerated: true,
          aiModelVersion: 'v1.0'
        }
      });
    }
  }

  async executeModerationAction(actionData, caseId, moderatorId) {
    const action = await this.prisma.moderatorAction.create({
      data: actionDto.create({
        ...actionData,
        moderationCaseId: caseId,
        moderatorId
      }),
      include: {
        moderator: true,
        targetUser: true,
        moderationCase: true
      }
    });

    // Execute specific action logic
    await this.executeActionLogic(actionData, action);

    // Log the action
    await this.logAction(LOG_TYPE.ACTION_TAKEN, {
      actionId: action.id,
      caseId,
      actionType: actionData.actionType,
      moderatorId
    }, moderatorId);

    return action;
  }

  async executeActionLogic(actionData, action) {
    switch (actionData.actionType) {
      case ACTION_TYPE.CONTENT_REMOVAL:
        await this.removeContent(actionData.targetContentType, actionData.targetContentId);
        break;
      
      case ACTION_TYPE.USER_SUSPENSION:
        await this.suspendUser(actionData.targetUserId, actionData.durationDays);
        break;
      
      case ACTION_TYPE.USER_BAN:
        await this.banUser(actionData.targetUserId);
        break;
      
      case ACTION_TYPE.TRUST_DEDUCTION:
        await this.adjustTrustScore(actionData.targetUserId, actionData.trustScoreChange);
        break;
    }
  }

  async removeContent(contentType, contentId) {
    if (contentType === 'post') {
      await this.prisma.post.update({
        where: { id: contentId },
        data: { deletedAt: new Date() }
      });
    } else if (contentType === 'comment') {
      await this.prisma.comment.update({
        where: { id: contentId },
        data: { deletedAt: new Date() }
      });
    }
  }

  async suspendUser(userId, durationDays) {
    // This would integrate with user management system
    // For now, we'll update the user's status
    const suspendedUntil = new Date();
    suspendedUntil.setDate(suspendedUntil.getDate() + durationDays);
    
    await this.prisma.user.update({
      where: { id: userId },
      data: { 
        isActive: false,
        // Add suspension end date field if needed
      }
    });
  }

  async banUser(userId) {
    await this.prisma.user.update({
      where: { id: userId },
      data: { 
        isActive: false,
        // Add ban status field if needed
      }
    });
  }

  async adjustTrustScore(userId, scoreChange) {
    const currentTrust = await this.prisma.trustScore.findUnique({
      where: { userId }
    });

    if (currentTrust) {
      const newScore = Math.max(0, Math.min(100, currentTrust.overallScore + scoreChange));
      await this.prisma.trustScore.update({
        where: { userId },
        data: { 
          overallScore: newScore,
          trustLevel: this.determineTrustLevel(newScore)
        }
      });
    }
  }

  async updateCaseStateAfterAction(caseId, actionType) {
    let newState = CASE_STATE.IN_PROGRESS;
    
    if (actionType === ACTION_TYPE.ESCALATE) {
      newState = CASE_STATE.PENDING_REVIEW;
    }

    await this.prisma.moderationCase.update({
      where: { id: caseId },
      data: { state: newState }
    });
  }

  async logAction(logType, details, userId = null) {
    await this.prisma.moderationLog.create({
      data: {
        logType,
        userId,
        details,
        // Add IP, user agent, session ID from request context if available
      }
    });
  }
}

export default ModerationService;
