/**
 * Moderation System Validation Schemas
 * Week-3 Ownership Feature Build
 * Input validation and sanitization
 */

import { REPORT_SEVERITY, REPORT_STATUS, ACTION_TYPE, TRUST_LEVEL, APPEAL_STATUS, FLAG_TYPE, CONTENT_TYPE } from './constants.js';

export const createReportSchema = {
  body: {
    type: 'object',
    required: ['flagType', 'reason'],
    properties: {
      reportedUserId: { type: 'integer', minimum: 1 },
      reportedPostId: { type: 'integer', minimum: 1 },
      reportedCommentId: { type: 'integer', minimum: 1 },
      severity: { 
        type: 'string', 
        enum: Object.values(REPORT_SEVERITY),
        default: REPORT_SEVERITY.MEDIUM
      },
      flagType: { 
        type: 'string', 
        enum: Object.values(FLAG_TYPE)
      },
      reason: { 
        type: 'string', 
        minLength: 10, 
        maxLength: 500 
      },
      description: { 
        type: 'string', 
        maxLength: 2000 
      },
      evidenceUrls: { 
        type: 'array',
        items: { type: 'string', format: 'uri' },
        maxItems: 5
      }
    },
    additionalProperties: false,
    oneOf: [
      { required: ['reportedUserId'] },
      { required: ['reportedPostId'] },
      { required: ['reportedCommentId'] }
    ]
  }
};

export const getReportSchema = {
  params: {
    type: 'object',
    required: ['id'],
    properties: {
      id: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  }
};

export const getReportsSchema = {
  query: {
    type: 'object',
    properties: {
      status: { 
        type: 'string', 
        enum: Object.values(REPORT_STATUS)
      },
      severity: { 
        type: 'string', 
        enum: Object.values(REPORT_SEVERITY)
      },
      flagType: { 
        type: 'string', 
        enum: Object.values(FLAG_TYPE)
      },
      reportedUserId: { type: 'integer', minimum: 1 },
      assignedModeratorId: { type: 'integer', minimum: 1 },
      page: { type: 'integer', minimum: 1, default: 1 },
      limit: { type: 'integer', minimum: 1, maximum: 100, default: 20 }
    },
    additionalProperties: false
  }
};

export const createCaseSchema = {
  body: {
    type: 'object',
    required: ['title'],
    properties: {
      title: { 
        type: 'string', 
        minLength: 5, 
        maxLength: 200 
      },
      description: { 
        type: 'string', 
        maxLength: 2000 
      },
      priority: { 
        type: 'string', 
        enum: Object.values(REPORT_SEVERITY),
        default: REPORT_SEVERITY.MEDIUM
      },
      assignedModeratorId: { type: 'integer', minimum: 1 },
      autoGenerated: { type: 'boolean', default: false }
    },
    additionalProperties: false
  }
};

export const assignCaseSchema = {
  params: {
    type: 'object',
    required: ['id'],
    properties: {
      id: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  },
  body: {
    type: 'object',
    required: ['assignedModeratorId'],
    properties: {
      assignedModeratorId: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  }
};

export const takeActionSchema = {
  params: {
    type: 'object',
    required: ['id'],
    properties: {
      id: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  },
  body: {
    type: 'object',
    required: ['actionType'],
    properties: {
      actionType: { 
        type: 'string', 
        enum: Object.values(ACTION_TYPE)
      },
      actionDetails: { 
        type: 'string', 
        maxLength: 1000 
      },
      targetUserId: { type: 'integer', minimum: 1 },
      targetContentType: { 
        type: 'string', 
        enum: Object.values(CONTENT_TYPE)
      },
      targetContentId: { type: 'integer', minimum: 1 },
      durationDays: { 
        type: 'integer', 
        minimum: 1, 
        maximum: 365 
      },
      trustScoreChange: { 
        type: 'integer', 
        minimum: -50, 
        maximum: 50 
      }
    },
    additionalProperties: false,
    if: {
      properties: { actionType: { const: ACTION_TYPE.USER_SUSPENSION } }
    },
    then: {
      required: ['durationDays']
    }
  }
};

export const resolveCaseSchema = {
  params: {
    type: 'object',
    required: ['id'],
    properties: {
      id: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  },
  body: {
    type: 'object',
    properties: {
      resolutionNotes: { 
        type: 'string', 
        maxLength: 1000 
      },
      finalStatus: { 
        type: 'string', 
        enum: ['RESOLVED', 'CLOSED']
      }
    },
    additionalProperties: false
  }
};

export const createAppealSchema = {
  body: {
    type: 'object',
    required: ['moderationCaseId', 'appealReason'],
    properties: {
      moderationCaseId: { type: 'integer', minimum: 1 },
      originalActionId: { type: 'integer', minimum: 1 },
      appealReason: { 
        type: 'string', 
        minLength: 10, 
        maxLength: 500 
      },
      appealDescription: { 
        type: 'string', 
        maxLength: 2000 
      },
      evidenceUrls: { 
        type: 'array',
        items: { type: 'string', format: 'uri' },
        maxItems: 5
      }
    },
    additionalProperties: false
  }
};

export const updateAppealSchema = {
  params: {
    type: 'object',
    required: ['id'],
    properties: {
      id: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  },
  body: {
    type: 'object',
    required: ['status', 'reviewNotes'],
    properties: {
      status: { 
        type: 'string', 
        enum: Object.values(APPEAL_STATUS)
      },
      reviewNotes: { 
        type: 'string', 
        minLength: 10, 
        maxLength: 1000 
      },
      finalDecision: { 
        type: 'string', 
        enum: ['uphold', 'reverse', 'modify']
      }
    },
    additionalProperties: false
  }
};

export const getDashboardSchema = {
  query: {
    type: 'object',
    properties: {
      moderatorId: { type: 'integer', minimum: 1 },
      dateRange: { 
        type: 'string',
        enum: ['today', 'week', 'month', 'year']
      },
      includeMetrics: { type: 'boolean', default: true }
    },
    additionalProperties: false
  }
};

export const getModerationLogsSchema = {
  query: {
    type: 'object',
    properties: {
      logType: { type: 'string' },
      userId: { type: 'integer', minimum: 1 },
      caseId: { type: 'integer', minimum: 1 },
      actionId: { type: 'integer', minimum: 1 },
      page: { type: 'integer', minimum: 1, default: 1 },
      limit: { type: 'integer', minimum: 1, maximum: 100, default: 50 },
      startDate: { type: 'string', format: 'date-time' },
      endDate: { type: 'string', format: 'date-time' }
    },
    additionalProperties: false
  }
};

export const updateTrustScoreSchema = {
  params: {
    type: 'object',
    required: ['userId'],
    properties: {
      userId: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  },
  body: {
    type: 'object',
    properties: {
      contentQualityScore: { 
        type: 'integer', 
        minimum: 0, 
        maximum: 100 
      },
      communityEngagementScore: { 
        type: 'integer', 
        minimum: 0, 
        maximum: 100 
      },
      reliabilityScore: { 
        type: 'integer', 
        minimum: 0, 
        maximum: 100 
      },
      trustLevel: { 
        type: 'string', 
        enum: Object.values(TRUST_LEVEL)
      }
    },
    additionalProperties: false,
    minProperties: 1
  }
};

export const escalateCaseSchema = {
  params: {
    type: 'object',
    required: ['id'],
    properties: {
      id: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  },
  body: {
    type: 'object',
    required: ['escalationReason'],
    properties: {
      escalationReason: { 
        type: 'string', 
        minLength: 10, 
        maxLength: 1000 
      },
      escalatedAdminId: { type: 'integer', minimum: 1 }
    },
    additionalProperties: false
  }
};
