import request from 'supertest';
import { describe, it, expect, beforeEach, afterEach } from '@jest/globals';
import dotenv from 'dotenv';
dotenv.config();

import { app } from '../../index.js';
import { REPORT_SEVERITY, CASE_STATE, ACTION_TYPE, TRUST_LEVEL } from '../../src/modules/moderation/constants.js';

describe('Moderation Cases API', () => {
  let moderatorToken;
  let adminToken;
  let userToken;
  let postId;
  let caseId;
  let userId;
  let moderatorId;
  let adminId;

  beforeEach(async () => {
    const unique = Date.now();

    // Create users
    const userRes = await request(app).post('/api/auth/register').send({
      name: 'Test User',
      email: `user+${unique}@example.com`,
      password: 'password123',
    });
    userToken = userRes.body.token;
    userId = userRes.body.user.id;

    const moderatorRes = await request(app).post('/api/auth/register').send({
      name: 'Test Moderator',
      email: `moderator+${unique}@example.com`,
      password: 'password123',
    });
    moderatorToken = moderatorRes.body.token;
    moderatorId = moderatorRes.body.user.id;

    const adminRes = await request(app).post('/api/auth/register').send({
      name: 'Test Admin',
      email: `admin+${unique}@example.com`,
      password: 'password123',
    });
    adminToken = adminRes.body.token;
    adminId = adminRes.body.user.id;

    // Update roles (in real implementation, this would be done via admin panel)
    await request(app)
      .patch(`/api/users/${moderatorId}/role`)
      .set('Authorization', `Bearer ${adminToken}`)
      .send({ role: 'MODERATOR' });

    await request(app)
      .patch(`/api/users/${adminId}/role`)
      .set('Authorization', `Bearer ${adminToken}`)
      .send({ role: 'ADMIN' });

    // Create test post
    const postRes = await request(app)
      .post('/api/posts')
      .set('Authorization', `Bearer ${userToken}`)
      .send({ 
        title: 'Test Post for Cases', 
        content: 'This is a test post content for case management testing', 
        tags: ['test'] 
      });
    postId = postRes.body.post.id;
  });

  describe('POST /moderation/cases', () => {
    it('should allow admins to create moderation cases', async () => {
      const caseData = {
        title: 'Test Moderation Case',
        description: 'This is a test case for moderation',
        priority: REPORT_SEVERITY.MEDIUM
      };

      const res = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send(caseData);

      expect(res.statusCode).toBe(201);
      expect(res.body.moderationCase).toBeDefined();
      expect(res.body.moderationCase.title).toBe(caseData.title);
      expect(res.body.moderationCase.caseNumber).toMatch(/^CASE-\d{4}-\d{5}$/);
      expect(res.body.moderationCase.state).toBe(CASE_STATE.OPEN);
      caseId = res.body.moderationCase.id;
    });

    it('should reject non-admins from creating cases', async () => {
      const caseData = {
        title: 'Unauthorized Case',
        description: 'This should fail'
      };

      const res = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(caseData);

      expect(res.statusCode).toBe(403);
    });

    it('should reject regular users from creating cases', async () => {
      const caseData = {
        title: 'User Case',
        description: 'This should fail'
      };

      const res = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${userToken}`)
        .send(caseData);

      expect(res.statusCode).toBe(403);
    });

    it('should validate required fields for case creation', async () => {
      const res = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          description: 'Missing title'
        });

      expect(res.statusCode).toBe(400);
    });

    it('should allow auto-generated cases', async () => {
      const caseData = {
        title: 'Auto-generated Case',
        description: 'System generated case',
        priority: REPORT_SEVERITY.HIGH,
        autoGenerated: true
      };

      const res = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send(caseData);

      expect(res.statusCode).toBe(201);
      expect(res.body.moderationCase.autoGenerated).toBe(true);
    });
  });

  describe('POST /moderation/cases/:id/assign', () => {
    beforeEach(async () => {
      // Create a case for testing
      const caseRes = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          title: 'Test Case for Assignment',
          description: 'Case to test assignment functionality'
        });
      caseId = caseRes.body.moderationCase.id;
    });

    it('should allow admins to assign cases to moderators', async () => {
      const res = await request(app)
        .post(`/api/moderation/cases/${caseId}/assign`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          assignedModeratorId: moderatorId
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.moderationCase.assignedModeratorId).toBe(moderatorId);
      expect(res.body.moderationCase.state).toBe(CASE_STATE.ASSIGNED);
    });

    it('should reject moderators from assigning cases', async () => {
      const res = await request(app)
        .post(`/api/moderation/cases/${caseId}/assign`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send({
          assignedModeratorId: moderatorId
        });

      expect(res.statusCode).toBe(403);
    });

    it('should validate moderator exists when assigning', async () => {
      const res = await request(app)
        .post(`/api/moderation/cases/${caseId}/assign`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          assignedModeratorId: 99999
        });

      expect(res.statusCode).toBe(400);
    });

    it('should handle case assignment to self', async () => {
      // First make admin a moderator too (in real system, admins would have moderator privileges)
      const res = await request(app)
        .post(`/api/moderation/cases/${caseId}/assign`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          assignedModeratorId: adminId
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.moderationCase.assignedModeratorId).toBe(adminId);
    });
  });

  describe('POST /moderation/cases/:id/action', () => {
    let assignedCaseId;

    beforeEach(async () => {
      // Create and assign a case for testing
      const caseRes = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          title: 'Test Case for Actions',
          description: 'Case to test action functionality'
        });

      const assignRes = await request(app)
        .post(`/api/moderation/cases/${caseRes.body.moderationCase.id}/assign`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          assignedModeratorId: moderatorId
        });

      assignedCaseId = caseRes.body.moderationCase.id;
    });

    it('should allow assigned moderator to take actions', async () => {
      const actionData = {
        actionType: ACTION_TYPE.WARNING,
        actionDetails: 'Warning issued for inappropriate behavior',
        targetUserId: userId
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.action).toBeDefined();
      expect(res.body.action.actionType).toBe(ACTION_TYPE.WARNING);
      expect(res.body.action.moderatorId).toBe(moderatorId);
    });

    it('should allow admins to take actions on any case', async () => {
      const actionData = {
        actionType: ACTION_TYPE.NOTES_ONLY,
        actionDetails: 'Adding administrative notes'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.action.actionType).toBe(ACTION_TYPE.NOTES_ONLY);
    });

    it('should reject unassigned moderators from taking actions', async () => {
      // Create another moderator
      const unique = Date.now();
      const otherModRes = await request(app).post('/api/auth/register').send({
        name: 'Other Moderator',
        email: `othermod+${unique}@example.com`,
        password: 'password123',
      });
      const otherModToken = otherModRes.body.token;
      const otherModId = otherModRes.body.user.id;

      await request(app)
        .patch(`/api/users/${otherModId}/role`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ role: 'MODERATOR' });

      const actionData = {
        actionType: ACTION_TYPE.WARNING,
        actionDetails: 'Unauthorized action attempt'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${otherModToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(403);
    });

    it('should handle content removal actions', async () => {
      const actionData = {
        actionType: ACTION_TYPE.CONTENT_REMOVAL,
        actionDetails: 'Removing spam content',
        targetContentType: 'post',
        targetContentId: postId
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.action.targetContentType).toBe('post');
      expect(res.body.action.targetContentId).toBe(postId);
    });

    it('should handle trust score adjustments', async () => {
      const actionData = {
        actionType: ACTION_TYPE.TRUST_DEDUCTION,
        actionDetails: 'Deducting trust points for violation',
        targetUserId: userId,
        trustScoreChange: -10
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.action.trustScoreChange).toBe(-10);
    });

    it('should validate suspension actions require duration', async () => {
      const actionData = {
        actionType: ACTION_TYPE.USER_SUSPENSION,
        actionDetails: 'Suspending user',
        targetUserId: userId
        // Missing durationDays
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${adminToken}`) // Only admins can suspend
        .send(actionData);

      expect(res.statusCode).toBe(400);
    });

    it('should handle user suspension actions', async () => {
      const actionData = {
        actionType: ACTION_TYPE.USER_SUSPENSION,
        actionDetails: 'Suspending user for policy violation',
        targetUserId: userId,
        durationDays: 7
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${adminToken}`) // Only admins can suspend
        .send(actionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.action.durationDays).toBe(7);
    });

    it('should reject moderators from suspending users', async () => {
      const actionData = {
        actionType: ACTION_TYPE.USER_SUSPENSION,
        actionDetails: 'Attempting suspension',
        targetUserId: userId,
        durationDays: 7
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(403);
    });

    it('should handle escalation actions', async () => {
      const actionData = {
        actionType: ACTION_TYPE.ESCALATE,
        actionDetails: 'Escalating to admin review'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/action`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(actionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.action.actionType).toBe(ACTION_TYPE.ESCALATE);
    });
  });

  describe('POST /moderation/cases/:id/resolve', () => {
    let assignedCaseId;

    beforeEach(async () => {
      // Create and assign a case for testing
      const caseRes = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          title: 'Test Case for Resolution',
          description: 'Case to test resolution functionality'
        });

      await request(app)
        .post(`/api/moderation/cases/${caseRes.body.moderationCase.id}/assign`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          assignedModeratorId: moderatorId
        });

      assignedCaseId = caseRes.body.moderationCase.id;
    });

    it('should allow assigned moderator to resolve cases', async () => {
      const resolutionData = {
        resolutionNotes: 'Case resolved after investigation'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/resolve`)
        .set('Authorization', `Bearer ${moderatorToken}`)
        .send(resolutionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.moderationCase.state).toBe(CASE_STATE.RESOLVED);
      expect(res.body.moderationCase.resolvedAt).toBeDefined();
    });

    it('should allow admins to resolve any case', async () => {
      const resolutionData = {
        resolutionNotes: 'Admin resolution',
        finalStatus: 'CLOSED'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/resolve`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send(resolutionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.moderationCase.state).toBe('CLOSED');
    });

    it('should reject unassigned moderators from resolving cases', async () => {
      // Create another moderator
      const unique = Date.now();
      const otherModRes = await request(app).post('/api/auth/register').send({
        name: 'Other Moderator',
        email: `othermod+${unique}@example.com`,
        password: 'password123',
      });
      const otherModToken = otherModRes.body.token;
      const otherModId = otherModRes.body.user.id;

      await request(app)
        .patch(`/api/users/${otherModId}/role`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ role: 'MODERATOR' });

      const resolutionData = {
        resolutionNotes: 'Unauthorized resolution attempt'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/resolve`)
        .set('Authorization', `Bearer ${otherModToken}`)
        .send(resolutionData);

      expect(res.statusCode).toBe(403);
    });

    it('should handle resolution with different final statuses', async () => {
      const resolutionData = {
        resolutionNotes: 'Closing case without action',
        finalStatus: 'CLOSED'
      };

      const res = await request(app)
        .post(`/api/moderation/cases/${assignedCaseId}/resolve`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send(resolutionData);

      expect(res.statusCode).toBe(200);
      expect(res.body.moderationCase.state).toBe('CLOSED');
    });
  });

  describe('GET /moderation/cases', () => {
    beforeEach(async () => {
      // Create multiple cases for testing
      for (let i = 0; i < 3; i++) {
        await request(app)
          .post('/api/moderation/cases')
          .set('Authorization', `Bearer ${adminToken}`)
          .send({
            title: `Test Case ${i + 1}`,
            description: `Description for case ${i + 1}`,
            priority: i % 2 === 0 ? REPORT_SEVERITY.LOW : REPORT_SEVERITY.HIGH
          });
      }
    });

    it('should allow moderators to view cases', async () => {
      const res = await request(app)
        .get('/api/moderation/cases')
        .set('Authorization', `Bearer ${moderatorToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.cases).toBeDefined();
      expect(res.body.cases.length).toBeGreaterThanOrEqual(3);
    });

    it('should reject non-moderators from viewing cases', async () => {
      const res = await request(app)
        .get('/api/moderation/cases')
        .set('Authorization', `Bearer ${userToken}`);

      expect(res.statusCode).toBe(403);
    });

    it('should filter cases by state', async () => {
      const res = await request(app)
        .get('/api/moderation/cases?state=OPEN')
        .set('Authorization', `Bearer ${moderatorToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.cases.every(case_ => case_.state === CASE_STATE.OPEN)).toBe(true);
    });

    it('should filter cases by priority', async () => {
      const res = await request(app)
        .get('/api/moderation/cases?priority=HIGH')
        .set('Authorization', `Bearer ${moderatorToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.cases.every(case_ => case_.priority === REPORT_SEVERITY.HIGH)).toBe(true);
    });

    it('should filter cases by assigned moderator', async () => {
      // First assign a case
      const casesRes = await request(app)
        .get('/api/moderation/cases')
        .set('Authorization', `Bearer ${moderatorToken}`);

      if (casesRes.body.cases.length > 0) {
        const caseId = casesRes.body.cases[0].id;
        
        await request(app)
          .post(`/api/moderation/cases/${caseId}/assign`)
          .set('Authorization', `Bearer ${adminToken}`)
          .send({ assignedModeratorId: moderatorId });

        const filteredRes = await request(app)
          .get(`/api/moderation/cases?assignedModeratorId=${moderatorId}`)
          .set('Authorization', `Bearer ${moderatorToken}`);

        expect(filteredRes.statusCode).toBe(200);
        expect(filteredRes.body.cases.every(case_ => case_.assignedModeratorId === moderatorId)).toBe(true);
      }
    });

    it('should paginate case results', async () => {
      const res = await request(app)
        .get('/api/moderation/cases?page=1&limit=2')
        .set('Authorization', `Bearer ${moderatorToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.cases.length).toBeLessThanOrEqual(2);
      expect(res.body.meta).toBeDefined();
    });
  });

  describe('GET /moderation/cases/:id', () => {
    let testCaseId;

    beforeEach(async () => {
      // Create a case for testing
      const caseRes = await request(app)
        .post('/api/moderation/cases')
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          title: 'Detailed Test Case',
          description: 'Case with full details for testing'
        });
      testCaseId = caseRes.body.moderationCase.id;
    });

    it('should allow moderators to view case details', async () => {
      const res = await request(app)
        .get(`/api/moderation/cases/${testCaseId}`)
        .set('Authorization', `Bearer ${moderatorToken}`);

      expect(res.statusCode).toBe(200);
      expect(res.body.moderationCase.id).toBe(testCaseId);
      expect(res.body.moderationCase.title).toBe('Detailed Test Case');
    });

    it('should reject non-moderators from viewing case details', async () => {
      const res = await request(app)
        .get(`/api/moderation/cases/${testCaseId}`)
        .set('Authorization', `Bearer ${userToken}`);

      expect(res.statusCode).toBe(403);
    });

    it('should return 404 for non-existent case', async () => {
      const res = await request(app)
        .get('/api/moderation/cases/99999')
        .set('Authorization', `Bearer ${moderatorToken}`);

      expect(res.statusCode).toBe(404);
    });
  });
});
