/**
 * Moderation Test Suite Configuration
 * Week-3 Ownership Feature Build
 * Test setup and utilities for moderation system
 */

import { beforeAll, afterAll, beforeEach, afterEach } from '@jest/globals';
import { PrismaClient } from '@prisma/client';

// Test database setup
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL_TEST || process.env.DATABASE_URL
    }
  }
});

// Global test setup
beforeAll(async () => {
  // Setup test database
  console.log('Setting up moderation test suite...');
  
  // Ensure test database is clean
  await cleanupTestData();
});

afterAll(async () => {
  // Cleanup test database
  await cleanupTestData();
  await prisma.$disconnect();
});

beforeEach(async () => {
  // Clean up before each test
  await cleanupTestData();
});

afterEach(async () => {
  // Clean up after each test
  await cleanupTestData();
});

async function cleanupTestData() {
  // Clean up in correct order due to foreign key constraints
  const tables = [
    'moderation_logs',
    'appeals',
    'moderator_actions',
    'content_flags',
    'user_flags',
    'trust_scores',
    'reports',
    'moderation_cases',
    'messages',
    'conversation_members',
    'conversations',
    'bookings',
    'slots',
    'mentorships',
    'collaboration_members',
    'collaborations',
    'event_attendees',
    'events',
    'followers',
    'likes',
    'comments',
    'post_tags',
    'tags',
    'posts',
    'users',
    'roles'
  ];

  for (const table of tables) {
    try {
      await prisma.$executeRawUnsafe(`DELETE FROM ${table}`);
    } catch (error) {
      // Table might not exist or be empty, continue
    }
  }

  // Reset sequences
  try {
    await prisma.$executeRawUnsafe(`
      SELECT setval(pg_get_serial_sequence('reports', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('moderation_cases', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('moderator_actions', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('trust_scores', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('appeals', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('moderation_logs', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('users', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('posts', 'id'), 1, false);
      SELECT setval(pg_get_serial_sequence('comments', 'id'), 1, false);
    `);
  } catch (error) {
    // Ignore sequence reset errors
  }
}

// Test utilities
export const createTestUser = async (userData = {}) => {
  const defaultUser = {
    name: 'Test User',
    email: `test-${Date.now()}@example.com`,
    password: 'password123',
    role: 'USER',
    ...userData
  };

  return await prisma.user.create({
    data: defaultUser
  });
};

export const createTestModerator = async (moderatorData = {}) => {
  const defaultModerator = {
    name: 'Test Moderator',
    email: `moderator-${Date.now()}@example.com`,
    password: 'password123',
    role: 'MODERATOR',
    ...moderatorData
  };

  return await prisma.user.create({
    data: defaultModerator
  });
};

export const createTestAdmin = async (adminData = {}) => {
  const defaultAdmin = {
    name: 'Test Admin',
    email: `admin-${Date.now()}@example.com`,
    password: 'password123',
    role: 'ADMIN',
    ...adminData
  };

  return await prisma.user.create({
    data: defaultAdmin
  });
};

export const createTestPost = async (postData = {}) => {
  const user = await createTestUser();
  
  const defaultPost = {
    title: 'Test Post',
    content: 'This is a test post content',
    authorId: user.id,
    status: 'APPROVED',
    ...postData
  };

  return await prisma.post.create({
    data: defaultPost,
    include: { author: true }
  });
};

export const createTestReport = async (reportData = {}) => {
  const reporter = await createTestUser();
  const post = await createTestPost();
  
  const defaultReport = {
    reporterId: reporter.id,
    reportedPostId: post.id,
    flagType: 'SPAM',
    reason: 'Test report',
    severity: 'MEDIUM',
    status: 'PENDING',
    ...reportData
  };

  return await prisma.report.create({
    data: defaultReport,
    include: {
      reporter: true,
      reportedPost: true,
      reportedUser: true
    }
  });
};

export const createTestModerationCase = async (caseData = {}) => {
  const defaultCase = {
    title: 'Test Moderation Case',
    description: 'Test case description',
    priority: 'MEDIUM',
    state: 'OPEN',
    autoGenerated: false,
    ...caseData
  };

  return await prisma.moderationCase.create({
    data: defaultCase,
    include: {
      assignedModerator: true,
      reports: true,
      actions: true
    }
  });
};

export const createTestAppeal = async (appealData = {}) => {
  const appellant = await createTestUser();
  const moderationCase = await createTestModerationCase();
  
  const defaultAppeal = {
    moderationCaseId: moderationCase.id,
    appellantUserId: appellant.id,
    appealReason: 'Test appeal',
    appealDescription: 'Test appeal description',
    status: 'SUBMITTED',
    ...appealData
  };

  return await prisma.appeal.create({
    data: defaultAppeal,
    include: {
      appellant: true,
      moderationCase: true,
      originalAction: true
    }
  });
};

export const createTestTrustScore = async (trustData = {}) => {
  const user = await createTestUser();
  
  const defaultTrustScore = {
    userId: user.id,
    overallScore: 50,
    trustLevel: 'NEW',
    contentQualityScore: 50,
    communityEngagementScore: 50,
    reliabilityScore: 50,
    ...trustData
  };

  return await prisma.trustScore.create({
    data: defaultTrustScore,
    include: { user: true }
  });
};

// Mock data generators
export const generateMockReportData = (overrides = {}) => ({
  reportedUserId: null,
  reportedPostId: null,
  reportedCommentId: null,
  severity: 'MEDIUM',
  flagType: 'SPAM',
  reason: 'Test report reason',
  description: 'Test report description',
  evidenceUrls: [],
  ...overrides
});

export const generateMockActionData = (overrides = {}) => ({
  actionType: 'WARNING',
  actionDetails: 'Test action details',
  targetUserId: null,
  targetContentType: null,
  targetContentId: null,
  durationDays: null,
  trustScoreChange: 0,
  isAutomatic: false,
  systemReason: null,
  ...overrides
});

export const generateMockAppealData = (overrides = {}) => ({
  moderationCaseId: null,
  originalActionId: null,
  appealReason: 'Test appeal reason',
  appealDescription: 'Test appeal description',
  evidenceUrls: [],
  ...overrides
});

// Test assertions
export const expectValidReport = (report) => {
  expect(report).toBeDefined();
  expect(report.id).toBeDefined();
  expect(report.flagType).toBeDefined();
  expect(report.reason).toBeDefined();
  expect(report.severity).toBeDefined();
  expect(report.status).toBeDefined();
  expect(report.createdAt).toBeDefined();
};

export const expectValidModerationCase = (case_) => {
  expect(case_).toBeDefined();
  expect(case_.id).toBeDefined();
  expect(case_.caseNumber).toBeDefined();
  expect(case_.title).toBeDefined();
  expect(case_.priority).toBeDefined();
  expect(case_.state).toBeDefined();
  expect(case_.createdAt).toBeDefined();
  expect(case_.caseNumber).toMatch(/^CASE-\d{4}-\d{5}$/);
};

export const expectValidAppeal = (appeal) => {
  expect(appeal).toBeDefined();
  expect(appeal.id).toBeDefined();
  expect(appeal.status).toBeDefined();
  expect(appeal.appealReason).toBeDefined();
  expect(appeal.createdAt).toBeDefined();
};

export const expectValidTrustScore = (trustScore) => {
  expect(trustScore).toBeDefined();
  expect(trustScore.userId).toBeDefined();
  expect(trustScore.overallScore).toBeGreaterThanOrEqual(0);
  expect(trustScore.overallScore).toBeLessThanOrEqual(100);
  expect(trustScore.trustLevel).toBeDefined();
  expect(trustScore.lastCalculatedAt).toBeDefined();
};

// Performance testing utilities
export const measureResponseTime = async (operation) => {
  const start = Date.now();
  const result = await operation();
  const end = Date.now();
  
  return {
    result,
    responseTime: end - start
  };
};

export const expectReasonableResponseTime = (responseTime, maxTime = 2000) => {
  expect(responseTime).toBeLessThan(maxTime);
};

// Security testing utilities
export const testSqlInjection = async (endpoint, data, authToken) => {
  const sqlInjectionPayloads = [
    "'; DROP TABLE users; --",
    "' OR '1'='1",
    "'; SELECT * FROM users; --",
    "' UNION SELECT * FROM users --"
  ];

  const results = [];
  
  for (const payload of sqlInjectionPayloads) {
    const testData = { ...data, reason: payload };
    
    const response = await request(app)
      .post(endpoint)
      .set('Authorization', `Bearer ${authToken}`)
      .send(testData);
    
    results.push({
      payload,
      statusCode: response.statusCode,
      shouldNotCrash: response.statusCode < 500
    });
  }
  
  return results;
};

export const testXssPrevention = async (endpoint, data, authToken) => {
  const xssPayloads = [
    '<script>alert("xss")</script>',
    'javascript:alert("xss")',
    '<img src="x" onerror="alert(\'xss\')">',
    '"><script>alert("xss")</script>'
  ];

  const results = [];
  
  for (const payload of xssPayloads) {
    const testData = { ...data, description: payload };
    
    const response = await request(app)
      .post(endpoint)
      .set('Authorization', `Bearer ${authToken}`)
      .send(testData);
    
    const isSanitized = response.statusCode === 201 && 
                       !response.body.description?.includes('<script>');
    
    results.push({
      payload,
      statusCode: response.statusCode,
      isSanitized
    });
  }
  
  return results;
};

// Export prisma for use in tests
export { prisma };

// Global test configuration
export const testConfig = {
  timeout: 10000, // 10 seconds per test
  retry: 2, // Retry failed tests twice
  parallel: true, // Run tests in parallel
  verbose: true // Verbose output
};
